const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function historyReport(rows,{from,to,language='zh'}={}){
 const en=/^en\b/i.test(language),t=(zh,english)=>en?english:zh;
 const states={submitted:t('已签到','Checked in'),completed:t('已签到','Checked in'),available:t('可签到','Available'),expired:t('已过期','Expired'),ready:t('等待匹配','Awaiting match'),review:t('需要核对','Needs review'),uncertain:t('结果待确认','Unconfirmed'),attempting:t('核对提交结果','Verifying submission'),waiting_code:t('等待签到码','Awaiting code'),unknown:t('未知','Unknown')};
 const evidence={'local-record':t('本机收集记录','Local collection'),'website-observed':t('网站实读记录','Observed on website'),'projected-current-schedule':t('按当前课表推算','Projected from current timetable')};
 const title=t('马莫 · 学期签到报告','Mamo · Attendance report');
 const headers=[t('日期','Date'),t('时间','Time'),t('课程 / 场次','Course / Session'),t('签到码','Code'),t('本机记录状态','Local record status'),t('网站状态','Website status'),t('依据 / 来源','Evidence / Source')];
 const body=rows.map(row=>{
  let link='';try{const url=new URL(row.sourceUrl);if(url.protocol==='https:')link=`<a href="${escape(url.href)}" rel="noreferrer noopener" target="_blank">${t('查看来源','View source')}</a>`;}catch{}
  const projected=row.evidence==='projected-current-schedule';
  return `<tr${projected?' class="projected"':''}><td>${escape(row.date)}</td><td>${escape(row.time)}</td><td><strong>${escape(row.course)}</strong><small>${escape([row.type,row.group].filter(Boolean).join(' '))}</small></td><td class="code">${escape(row.code||'—')}</td><td>${escape(states[row.status]||row.status||'—')}</td><td>${escape(states[row.websiteState]||row.websiteState||states.unknown)}</td><td>${escape(evidence[row.evidence]||row.evidence)}${link}<small>${escape(row.observedAt||'')}</small></td></tr>`;
 }).join('');
 return `<!doctype html><html lang="${en?'en':'zh-CN'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7f9;color:#243945;font:14px/1.6 system-ui,-apple-system,sans-serif}main{max-width:1200px;margin:32px auto;padding:32px;background:white;border-top:5px solid #087bab}h1{font-size:26px;margin:0 0 10px}p{color:#667b86}.range{color:#087bab;font-weight:600}.note{padding:14px 16px;background:#f1f6f8;border-left:3px solid #91b6c7}.table{overflow:auto}table{width:100%;border-collapse:collapse;text-align:left}th{background:#edf4f7;font-size:12px;color:#506c7a;padding:12px}td{padding:14px 12px;border-bottom:1px solid #e1e9ed;vertical-align:top}small{display:block;color:#738690;font-size:11px}a{display:block;color:#087bab}.code{font-family:monospace;font-weight:700}.projected{background:#fffbed}footer{margin-top:24px;color:#7c8b93;font-size:12px}@media(max-width:600px){main{margin:0;padding:20px}h1{font-size:22px}}@media print{@page{size:A4 landscape;margin:12mm}body{background:white;font-size:10px}main{margin:0;padding:0;max-width:none}.table{overflow:visible}th,td{padding:8px}tr{break-inside:avoid}thead{display:table-header-group}a{color:inherit}}
</style></head><body><main><h1>${title}</h1><p class="range">${escape(from)} — ${escape(to)} · ${rows.length} ${t('条记录','records')}</p><p class="note">${t('仅汇总本机已保存的数据；导出不会重新检索 Gmail 或 Attendance。推算场次不代表实际上课或已签到，未知状态也不代表缺勤。','This report uses locally saved data only; exporting does not search Gmail or Attendance. Projected sessions do not confirm classes or attendance. Unknown status does not mean absence.')}</p><div class="table"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div><footer>Mamo Check-in · ${t('本机收集状态与网站实读状态分别列出。','Local collection and observed website status are shown separately.')}</footer></main></body></html>`;
}
